### ISSUE TITLE
🚨🚨🚨 u are under arest 👀 👀  FoR not checking ur numbers 🔢  🔢 

### ISSUE THREAD

**Issue by augustt198** [zelkatani/mat#2]
[💻 💣  my GUy not 👀  checking for that 👌👌👌   >>> ➗ DiVide ➗ by ➗ ZER:zero: ➗  <<< 👌👌👌 💥 wHAT??❓?❗️](https://github.com/ze/mat/blob/e5e4b08c5ba7d4367a553fee169b9e79f3f1bd83/src/matrix.c#L43) literally<sup>cornell<sup>level<sup>~engineering~ arts and scienes</sup></sup></sup>

**Comment by ze** [comment]
:eyes: wh:o2::o2::b:s

**Comment by ze** [comment]
ok they're looking fine now
